myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from picpart.views import index_view, detail_view, about_view, PictureListView, \
    PictureDetailView, PictureUpdateView, PictureDeleteView, PictureCreateView, PictureUpgradeCreateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', PictureListView.as_view()),
    path('picpart/<int:pk>/', PictureDetailView.as_view(), name="detail"),
    path('picpart/delete/<int:pk>/', PictureDeleteView.as_view()),
    path('picpart/edit/<int:pk>/', PictureUpdateView.as_view()),
    path('picpart/create/', PictureCreateView.as_view()),

    path('picpart/preview/create/<int:picture_id>/', PictureUpgradeCreateView.as_view(), name="upgrade"),

    path('about/', about_view),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/picpart/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Pictures(models.Model):
    objects = None
    name = models.CharField(max_length=100, unique=True)
    size = models.CharField(max_length=20)
    content = models.ImageField(upload_to='picpart', blank=True, null=True)
    tune = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class PictureInfo(models.Model):
    text = models.TextField(blank=True)
    picture = models.OneToOneField(Pictures, on_delete=models.CASCADE)


class PictureUpgrade(models.Model):
    name = models.CharField(max_length=100, unique=True)
    matrix = models.JSONField(default=dict)
    content = models.ImageField(upload_to='process', blank=True, null=True)
    picture = models.ForeignKey(Pictures, on_delete=models.CASCADE)
    tune = models.CharField(max_length=100)
    size_part = models.PositiveSmallIntegerField(default=12, blank=False, null=False)
    color_limit = models.PositiveSmallIntegerField(default=100, blank=False, null=False)
    width = models.PositiveSmallIntegerField(default=800, blank=False, null=False)

myproject/picpart/forms.py
from django import forms

from .models import Pictures, PictureUpgrade


class PictureForm(forms.ModelForm):
    name = forms.CharField(help_text='Название картинки',
                           widget=forms.TextInput(attrs={'class': 'form-control'}),
                           label='',
                           )

    content = forms.ImageField(help_text='',
                               widget=forms.FileInput(attrs={'class': 'form-control'}),
                               label='',
                               )

    class Meta:
        model = Pictures
        fields = ('name', 'content')


class PictureFormUpgrade(forms.ModelForm):
    name = forms.CharField(help_text='Название',
                           widget=forms.TextInput(attrs={'class': 'form-control'}),
                           label='',
                           )

    content = forms.ImageField(help_text='',
                               widget=forms.FileInput(attrs={'class': 'form-control'}),
                               label='',
                               )

    class Meta:
        model = PictureUpgrade
        fields = ('name', 'content', 'size_part', 'color_limit', 'width')

myproject/picpart/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

# from jcrosbot import getimage

from .models import Pictures, PictureUpgrade
from .tasks import save_pictures_task
from django.core.mail import send_mail
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from .forms import PictureForm, PictureFormUpgrade

'''На классах CBV generic'''


class PictureListView(ListView):
    model = Pictures
    template_name = 'picpart/index.html'
    # добавить пагинацию на странице
    # paginate_by = 10


class PictureDetailView(DetailView):
    model = Pictures
    template_name = 'picpart/detail.html'


class PictureUpdateView(UpdateView):
    model = Pictures
    template_name = 'picpart/edit.html'
    success_url = '/'
    # fields = '__all__'
    form_class = PictureForm


class PictureCreateView(CreateView):
    model = Pictures
    template_name = 'picpart/edit.html'
    success_url = '/'
    # fields = '__all__'
    form_class = PictureForm


class PictureDeleteView(DeleteView):
    model = Pictures
    template_name = 'picpart/delete_confirm.html'
    success_url = '/'


class PictureUpgradeCreateView(CreateView):
    model = PictureUpgrade
    template_name = 'picpart/upgrade.html'
    success_url = '/'
    form_class = PictureFormUpgrade

    # по self.picture найти картинку в БД и применить фильтры
    # вызвать бота, вернуть картинку в БД и отобразить

    def dispatch(self, request, *args, **kwargs):
        self.picture = get_object_or_404(Pictures, pk=kwargs['picture_id'])
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.picture = self.picture
        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        # obj = form.instance or self.object
        # переход на предыдущую
        return reverse("detail", kwargs={'pk': self.picture.pk})
        # переход на текущую
        # return self.request.path


'''На функциях'''


def index_view(request):
    pictures = Pictures.objects.all()
    if request.method == 'POST':
        # запустить RabbitMQ
        # save_pictures_task.delay()
        send_mail('Subject here', 'Here is the message.', 'from@example.com',
                  ['dmpinform@gmail.com'], fail_silently=False)
    return render(request, 'picpart/index.html', {'pictures': pictures})


def detail_view(request):
    picture_id = request.GET["picture_id"]
    picture = Pictures.objects.get(pk=picture_id)
    return render(request, 'picpart/detail.html', {'picture': picture})


def about_view(request):
    return render(request, 'picpart/about.html')

myproject/picpart/templates/picpart/about.html
{% extends "base.html" %}
{% block title %}
    О проекте
{% endblock %}

{% block content %}
       Описание проекта, инструкция
{% endblock %}

myproject/picpart/templates/picpart/delete_confirm.html
{% extends "base.html" %}
{% block title %}
    <img src="{{object.content.url}}" width="100px">
{% endblock %}

{% block content %}
    <div><h5>{{object.name}} ID = {{object.pk}}</h5></div>
        Вы уверены?
        <form method="post">
            {% csrf_token %}
            <a href="/" class="button">К моим рисункам</a>
             <button class="btn btn-danger" type="submit">Да</button>
        </form>
{% endblock %}

myproject/picpart/templates/picpart/detail.html
{% extends "base.html" %}
{% block title %}
    <img src="{{object.content.url}}" width="100px">
{% endblock %}

{% block content %}
    <div>
        <h5>{{object.name}} ID = {{object.pk}}</h5>
         <a href="/" class="button">К моим рисункам</a>
         <a href="/picpart/delete/{{object.pk}}/" class="button">Удалить</a>
         <a href="/picpart/edit/{{object.pk}}/" class="button">Изменить</a>
    </div>

     <div class="wrapper border-0 border-secondary exmp1">
        <a href="/picpart/preview/create/{{object.pk}}/">
          <img src="/media/picpart/newimage.png" alt="">
        </a>
      </div>

     <div>
         {% for pictupd in object.pictureupgrade_set.all %}
             <div class="wrapper border-1 exmp1">
               <a href="#">
                  <img src="{{ pictupd.content.url }}" alt="">
               </a>
           </div>
         {% endfor %}
     </div>

{% endblock %}

myproject/picpart/templates/picpart/edit.html
{% extends "base.html" %}
{% block title %}
  {{object.name}}
{% endblock %}

{% block content %}
<div class="bg-light p-5 rounded">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <hr>
<!--        {% for field in form %}-->
<!--            {{field.name}}-->
<!--            <div>-->
<!--                ...-->
<!--            </div>-->
<!--            <p></p>-->
<!--            {{field}}-->
<!--        {% endfor %}-->
        <button class="btn btn-outline-dark btn-sm px-2 py-0" type="submit">Сохранить</button>
        <a href="/" class="button">Отменить</a>
    </form>
</div>
{% endblock %}

myproject/picpart/templates/picpart/index.html
{% extends "base.html" %}
{% block title %}
{#    <h5>Главная</h5>#}
{% endblock %}

{% block content %}

      <div class="wrapper border-0 border-secondary exmp1">
        <a href="/picpart/create">
          <img src="/media/picpart/newimage.png" alt="">
        </a>
      </div>

           {% for item in object_list %}
                <div class="wrapper border-1 exmp1">
                   <a href="/picpart/{{ item.pk }}">
                      <img src="{{item.content.url}}" alt="">
                   </a>
               </div>
          {% endfor %}

    {#        <form method="post">#}
    {#            {% csrf_token %}#}
    {#            <button class="btn btn-primary" type="submit"> Сохранить </button>#}
    {#        </form>#}

{% endblock %}

myproject/picpart/templates/picpart/upgrade.html
{% extends "base.html" %}
{% block title %}
  {{object.name}}
{% endblock %}

{% block content %}
<div class="bg-light p-5 rounded">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <hr>
<!--        {% for field in form %}-->
<!--            {{field.name}}-->
<!--            <div>-->
<!--                ...-->
<!--            </div>-->
<!--            <p></p>-->
<!--            {{field}}-->
<!--        {% endfor %}-->
        <button class="btn btn-outline-dark btn-sm px-2 py-0" type="submit">Сохранить</button>
        <a href="/" class="button">Отменить</a>
    </form>
</div>
{% endblock %}